# Generated by Django 2.1.1 on 2018-09-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaVeiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cpf', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Passagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('valor_passagem', models.DecimalField(decimal_places=2, max_digits=8)),
                ('liberado', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10)),
                ('fabricante', models.CharField(blank=True, max_length=250, null=True)),
                ('modelo', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('veiculo',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False,
                                      to='SemPararUFMT.Veiculo')),
                ('tag_uid', models.CharField(max_length=20)),
                ('credito', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
            ],
        ),
        migrations.AddField(
            model_name='veiculo',
            name='categoria_veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SemPararUFMT.CategoriaVeiculo'),
        ),
        migrations.AddField(
            model_name='veiculo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SemPararUFMT.Cliente'),
        ),
        migrations.AddField(
            model_name='passagem',
            name='equipamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SemPararUFMT.Equipamento'),
        ),
    ]
